type = "about"
title = "About"

[profile]
research_interests = [
  "Human Movement Biomechanics",
  "Computer Simulations",
  "Machine Learning in Sports Science",
  "Wearable Technology",
]

[[sections]]
id = "about"
type = "markdown"
source = "bio.md"
title = "About"

[[sections]]
id = "Technical Stack"
type = "markdown"
source = "skills.md"
title = "Technical Stack"

[[sections]]
id = "featured_publications"
type = "publications"
title = "Selected Publications"
filter = "selected"
limit = 5

[[sections]]
id = "news"
type = "list"
title = "News"
source = "news.toml"

